CREATE PROC UPDATE_GOC
  @NGAY DATE,
  @MA_TK NVARCHAR(20)
AS
BEGIN
	DECLARE @TIEN_NHAN FLOAT
	DECLARE @NGAY_RUT DATE
	DECLARE @SOTIEN FLOAT
	DECLARE @LAI_SUAT FLOAT
	DECLARE @KY_HAN INT
	DECLARE @NGAY_GUI DATE
	DECLARE @NGAY_DEN_HAN DATE
	DECLARE @GIA_HAN INT
	DECLARE @A DATE
	SET @TIEN_NHAN = 0
	SET @NGAY_RUT = (SELECT NGAY_RUT FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	SET	@SOTIEN = (SELECT SOTIEN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK) 
	SET @LAI_SUAT = (SELECT LAISUAT FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	SET @KY_HAN = (SELECT KY_HAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	SET @NGAY_GUI = (SELECT NGAY_GUI FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	SET @NGAY_DEN_HAN = (SELECT NGAY_DENHAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	SET @GIA_HAN = (SELECT TUGIAHAN FROM TIENGUI_TIETKIEM WHERE MA_TAIKHOAN_TIETKIEM = @MA_TK)
	IF @NGAY_RUT IS NOT NULL

	BEGIN
		IF @NGAY >= @NGAY_RUT 
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + DATEDIFF(DAY,@NGAY_GUI,@NGAY_RUT)*0.1*@SOTIEN/36500
		END
		ELSE
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + DATEDIFF(DAY,@NGAY_GUI,@NGAY)*0.1*@SOTIEN/36500
		END
	END
	ELSE IF @NGAY_RUT IS NULL AND @GIA_HAN = 0
	BEGIN
		IF @NGAY < @NGAY_DEN_HAN
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + DATEDIFF(DAY,@NGAY_GUI,@NGAY)*0.1*@SOTIEN/36500
		END
		ELSE IF @NGAY = @NGAY_DEN_HAN
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + DATEDIFF(DAY,@NGAY_GUI,@NGAY_DEN_HAN)*@LAI_SUAT*@SOTIEN/36500
		END
		ELSE IF @NGAY > @NGAY_DEN_HAN
		BEGIN
			IF @NGAY_DEN_HAN IN (SELECT HolidayDate FROM Holidays) OR DATEPART(WEEKDAY,@NGAY_DEN_HAN) = 1
			BEGIN
				SET @A = @NGAY_DEN_HAN
				WHILE @A IN (SELECT HolidayDate FROM Holidays) OR DATEPART(WEEKDAY,@NGAY_DEN_HAN) = 1
				BEGIN
					SET @A = DATEADD(DAY,1,@A)
				END	
				SET @TIEN_NHAN = @SOTIEN + @SOTIEN*DATEDIFF(DAY,@A,@NGAY_DEN_HAN)*@LAI_SUAT/36500 + @SOTIEN*DATEDIFF(DAY,@A,@NGAY)*0.1/36500
			END
			ELSE
			BEGIN
				SET @TIEN_NHAN = @SOTIEN + @SOTIEN*DATEDIFF(DAY,@NGAY_DEN_HAN,@NGAY)*0.1/36500
			END
		END
	END
	ELSE IF @NGAY_RUT IS NULL AND @GIA_HAN = 1
	BEGIN
		IF @NGAY < @NGAY_DEN_HAN
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + DATEDIFF(DAY,@NGAY_GUI,@NGAY)*0.1*@SOTIEN/36500
		END
		ELSE IF @NGAY = @NGAY_DEN_HAN
		BEGIN
			SET @TIEN_NHAN = @SOTIEN + @SOTIEN*@LAI_SUAT*@KY_HAN/1200
		END
		ELSE IF @NGAY > @NGAY_DEN_HAN
		BEGIN
			WHILE @NGAY > @NGAY_DEN_HAN 
			BEGIN
				SET @SOTIEN = @SOTIEN + @SOTIEN*@LAI_SUAT*@KY_HAN/1200
				SET @NGAY_GUI =DATEADD(MONTH,@KY_HAN,@NGAY_GUI)
				SET @NGAY_DEN_HAN = DATEADD(MONTH,@KY_HAN,@NGAY_DEN_HAN)
			END
			IF @NGAY_GUI IN (SELECT HolidayDate FROM Holidays) OR DATEPART(WEEKDAY,@NGAY_GUI) = 1
			BEGIN
				SET @A = @NGAY_GUI
				WHILE @A IN (SELECT HolidayDate FROM Holidays) OR DATEPART(WEEKDAY,@NGAY_GUI) = 1
				BEGIN
					SET @A = DATEADD(DAY,1,@A)
				END	
				SET @TIEN_NHAN = @SOTIEN + @SOTIEN*DATEDIFF(DAY,@A,@NGAY_GUI)*@LAI_SUAT/36500 + @SOTIEN*DATEDIFF(DAY,@A,@NGAY)*0.1/36500
			END
			ELSE
			BEGIN
				SET @TIEN_NHAN = @SOTIEN + @SOTIEN*DATEDIFF(DAY,@NGAY_GUI,@NGAY)*0.1/36500
			END 
		END
	END
	SELECT ROUND(@TIEN_NHAN,0) AS N'SỐ TIỀN NHẬN'
END
EXEC UPDATE_GOC '2025-01-03','CSAV9080907'