CREATE PROC PRC_B16_4
	@YEAR INT
AS
BEGIN

DECLARE @TH TABLE
(
	ID			INT IDENTITY(1,1),
	TIEU_CHI	NVARCHAR(50),
	THUYETMINH	NVARCHAR(200),
	TAIKHOAN	NVARCHAR(20),
	SOTIEN		BIGINT
);
INSERT INTO @TH
SELECT 
	N'MỤC ĐÍCH',
	TEN_MUCDICH_CAP1,
	MA_HOPDONG_TINDUNG,
	SOTIEN
FROM HOPDONG_TINDUNG	A
LEFT JOIN MUCDICH_CAPTINDUNG B ON A.MA_MUCDICH_CAPTD = B.MA_MUCDICH_CAPTD 
WHERE YEAR(NGAY_GIAINGAN) = @YEAR
INSERT INTO @TH
SELECT 
	N'HÌNH THỨC',
	TEN_HINHTHUC_CAP1,
	MA_HOPDONG_TINDUNG,
	SOTIEN
FROM HOPDONG_TINDUNG		A
LEFT JOIN HINHTHUC_CAPTINDUNG	B ON A.MA_HINHTHUC_CAPTD = B.MA_HINHTHUC_CAPTD
WHERE YEAR(NGAY_GIAINGAN) = @YEAR
INSERT INTO @TH
SELECT 
	N'NGÀNH NGHỀ',
	TEN_NGANHNGHE_KINHTE_CAP01,
	MA_HOPDONG_TINDUNG,
	SOTIEN
FROM HOPDONG_TINDUNG		A
LEFT JOIN KHACHHANG				B ON A.MA_KHACHHANG = B.MA_KHACHHANG
LEFT JOIN NGANHNGHE_KINHTE_CAP03 C ON B.MA_NGANHNGHE_KINHTE = C.MA_NGANHNGHE_KINHTE_CAP03
LEFT JOIN NGANHNGHE_KINHTE_CAP01 D ON C.MA_NGANHNGHE_KINHTE_CAP01 = D.MA_NGANHNGHE_KINHTE_CAP01
WHERE YEAR(NGAY_GIAINGAN) = @YEAR

INSERT INTO @TH
SELECT 
	N'SẢN PHẨM',
	TENSP,
	MA_HOPDONG_TINDUNG,
	SOTIEN
FROM HOPDONG_TINDUNG A
LEFT JOIN SANPHAM_TINDUNG B ON A.MA_SANPHAM_TD = B.MASP
WHERE YEAR(NGAY_GIAINGAN) = @YEAR


DECLARE @BAOCAO TABLE
(
	ID INT IDENTITY(1,1),
	TIEUCHI1	NVARCHAR(4),
	TIEUCHI2	NVARCHAR(2),
	THUYETMINH	NVARCHAR(200),
	SO_HOPDONG	INT,
	TYLE		FLOAT,
	SOTIEN		BIGINT,
	TYLE2		FLOAT
)
--MỤC ĐÍCH


DECLARE @SUM_TK INT, @SUM_ST BIGINT
SELECT @SUM_TK = COUNT(TAIKHOAN) FROM @TH WHERE TIEU_CHI = N'MỤC ĐÍCH'
SELECT @SUM_ST = SUM(SOTIEN) FROM @TH WHERE TIEU_CHI = N'MỤC ĐÍCH'
INSERT INTO @BAOCAO VALUES ('I.','',N'Mục đích cấp tín dụng',@SUM_TK,100,@SUM_ST,100)
INSERT INTO @BAOCAO
SELECT 
	'I.',
	CONCAT('',ROW_NUMBER() OVER(ORDER BY THUYETMINH)),
	THUYETMINH,
	COUNT(TAIKHOAN),
	ROUND(cast(COUNT(TAIKHOAN) as decimal(10,2))*100/@SUM_TK,2),
	SUM(SOTIEN),
	ROUND(cast(SUM(SOTIEN)as decimal(20,2))*100/@SUM_ST,2)
FROM @TH
WHERE TIEU_CHI = N'MỤC ĐÍCH'
GROUP BY THUYETMINH
--HÌNH THỨC
SELECT @SUM_TK = COUNT(TAIKHOAN) FROM @TH WHERE TIEU_CHI = N'HÌNH THỨC'
SELECT @SUM_ST = SUM(SOTIEN) FROM @TH WHERE TIEU_CHI = N'HÌNH THỨC'
INSERT INTO @BAOCAO VALUES ('II.','',N'Hình thức cấp tín dụng',@SUM_TK,100,@SUM_ST,100)
INSERT INTO @BAOCAO
SELECT 
	'II.',
	CONCAT('',ROW_NUMBER() OVER(ORDER BY THUYETMINH)),
	THUYETMINH,
	COUNT(TAIKHOAN),
	ROUND(cast(COUNT(TAIKHOAN) as decimal(10,2))*100/@SUM_TK,2),
	SUM(SOTIEN),
	ROUND(cast(SUM(SOTIEN)as decimal(20,2))*100/@SUM_ST,2)
FROM @TH
WHERE TIEU_CHI = N'HÌNH THỨC'
GROUP BY THUYETMINH

--NGÀNH NGHỀ
SELECT @SUM_TK = COUNT(TAIKHOAN) FROM @TH WHERE TIEU_CHI = N'NGÀNH NGHỀ'
SELECT @SUM_ST = SUM(SOTIEN) FROM @TH WHERE TIEU_CHI = N'NGÀNH NGHỀ'
INSERT INTO @BAOCAO VALUES ('III.','',N'Theo ngành nghề kinh tế',@SUM_TK,100,@SUM_ST,100)
INSERT INTO @BAOCAO
SELECT 
	'III.',
	CONCAT('',ROW_NUMBER() OVER(ORDER BY THUYETMINH)),
	THUYETMINH,
	COUNT(TAIKHOAN),
	ROUND(cast(COUNT(TAIKHOAN) as decimal(10,2))*100/@SUM_TK,2),
	SUM(SOTIEN),
	ROUND(cast(SUM(SOTIEN)as decimal(20,2))*100/@SUM_ST,2)
FROM @TH
WHERE TIEU_CHI = N'NGÀNH NGHỀ'
GROUP BY THUYETMINH

--SẢN PHẨM
SELECT @SUM_TK = COUNT(TAIKHOAN) FROM @TH WHERE TIEU_CHI = N'SẢN PHẨM'
SELECT @SUM_ST = SUM(SOTIEN) FROM @TH WHERE TIEU_CHI = N'SẢN PHẨM'
INSERT INTO @BAOCAO VALUES ('IV.','',N'Theo sản phẩm tín dụng',@SUM_TK,100,@SUM_ST,100)
INSERT INTO @BAOCAO
SELECT 
	'IV.',
	CONCAT('',ROW_NUMBER() OVER(ORDER BY THUYETMINH)),
	THUYETMINH,
	COUNT(TAIKHOAN),
	ROUND(cast(COUNT(TAIKHOAN) as decimal(10,2))*100/@SUM_TK,2),
	SUM(SOTIEN),
	ROUND(cast(SUM(SOTIEN)as decimal(20,2))*100/@SUM_ST,2)
FROM @TH
WHERE TIEU_CHI = N'SẢN PHẨM'
GROUP BY THUYETMINH

SELECT 
	CONCAT(TIEUCHI1,TIEUCHI2,THUYETMINH) 'THUYẾT MINH',
	SO_HOPDONG,
	TYLE,
	SOTIEN,
	TYLE2
FROM @BAOCAO

END;

EXEC PRC_B16_4 2024