
CREATE TABLE KEHOACH_TRANO
(	ID				INT IDENTITY(1,1),
	MA_KHACHHANG	NVARCHAR(20),
	MA_HOPDONG_TINDUNG	NVARCHAR(20),
	NGAY_GIAI_NGAN	DATE,
	NGAY_DAOHAN		DATE,
	SOTIEN			NUMERIC(18,0),
	LAISUAT			FLOAT,
	KY_HAN			INT,
	NGAY_DAUKY		DATE,
	NGAY_CUOIKY		DATE,
	SO_NGAY			DECIMAL,
	DUNO_GOC		NUMERIC(18,0),
	GOC_PHAITRA		NUMERIC(18,0),
	LAI_PHAITRA		NUMERIC(18,0),
	TIEN_PHAITRA	NUMERIC(18,0)
);

DECLARE @MA_KH			NVARCHAR(20),
		@SOTIEN			NUMERIC(18,0),
		@NGAY_GIAI_NGAN	DATE,
		@NGAY_DAOHAN	DATE,
		@LAISUAT		FLOAT,
		@KY_HAN			INT,
		@NGAY_DAUKY		DATE,
		@NGAY_CUOIKY	DATE,
		@DUNO_GOC		NUMERIC(18,0),
		@GOC_PHAITRA	NUMERIC(18,0) = 0,
		@LAI_PHAITRA	NUMERIC(18,0) = 0,
		@TIEN_PHAITRA	NUMERIC(18,0),
		@SONGAY			DECIMAL,
		@i				DECIMAL, 
		 @MA_HDTD  NVARCHAR(20)
DECLARE CUR CURSOR FOR
SELECT MA_KHACHHANG, MA_HOPDONG_TINDUNG,SOTIEN,NGAY_GIAINGAN,NGAY_DAOHAN, LAISUAT,KY_HAN FROM HOPDONG_TINDUNG
OPEN CUR
FETCH NEXT FROM CUR
INTO @MA_KH, @MA_HDTD,@SOTIEN,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@LAISUAT,@KY_HAN
WHILE @@FETCH_STATUS = 0
BEGIN
	SET		@i				=	1
	SET		@NGAY_DAUKY		= @NGAY_GIAI_NGAN
	SET		@GOC_PHAITRA	=ROUND(@SOTIEN/@KY_HAN,0)
	SET		@DUNO_GOC		= @SOTIEN
	WHILE @i <= @KY_HAN
	BEGIN
		SET @NGAY_DAUKY		= DATEADD(MONTH,@i - 1,@NGAY_GIAI_NGAN)
		SET @NGAY_CUOIKY	= DATEADD(DAY,-1,(DATEADD(MONTH,@i,@NGAY_GIAI_NGAN)))
		SET @SONGAY			= DATEDIFF(DAY,@NGAY_DAUKY,@NGAY_CUOIKY) +1
		SET @LAI_PHAITRA	= ROUND(@DUNO_GOC*@SONGAY*@LAISUAT/36500,0)
		SET @TIEN_PHAITRA	= @GOC_PHAITRA +@LAI_PHAITRA
		INSERT INTO KEHOACH_TRANO VALUES (@MA_KH,@MA_HDTD,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@SOTIEN,@LAISUAT,@i,@NGAY_DAUKY,@NGAY_CUOIKY,@SONGAY,@DUNO_GOC,@GOC_PHAITRA,@LAI_PHAITRA,@TIEN_PHAITRA)
		SET	@DUNO_GOC		= @DUNO_GOC - @GOC_PHAITRA 
		SET @i = @i + 1
	END
	UPDATE KEHOACH_TRANO SET NGAY_CUOIKY = @NGAY_DAOHAN WHERE KY_HAN = @KY_HAN
	FETCH NEXT FROM CUR
	INTO @MA_KH, @MA_HDTD,@SOTIEN,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@LAISUAT,@KY_HAN
END
CLOSE CUR;
DEALLOCATE CUR;

SELECT * FROM KEHOACH_TRANO
