
CREATE TABLE KEHOACH_TRANO
(	ID				INT IDENTITY(1,1),
	MA_KHACHHANG	NVARCHAR(20),
	MA_HOPDONG_TINDUNG	NVARCHAR(20),
	NGAY_GIAI_NGAN	DATE,
	NGAY_DAOHAN		DATE,
	SOTIEN			NUMERIC(18,0),
	LAISUAT			DECIMAL,
	KY_HAN			DECIMAL,
	NGAY_DAUKY		DATE,
	NGAY_CUOIKY		DATE,
	SO_NGAY			DECIMAL,
	DUNO_GOC		NUMERIC(18,2),
	GOC_PHAITRA		NUMERIC(18,2),
	LAI_PHAITRA		NUMERIC(18,2),
	TIEN_PHAITRA	NUMERIC(18,2)
);

DECLARE @MA_KH			NVARCHAR(20),
		@SOTIEN			NUMERIC(18,2),
		@NGAY_GIAI_NGAN	DATE,
		@NGAY_DAOHAN	DATE,
		@LAISUAT		DECIMAL,
		@KY_HAN			DECIMAL,
		@NGAY_DAUKY		DATE,
		@NGAY_CUOIKY	DATE,
		@DUNO_GOC		NUMERIC(18,2),
		@GOC_PHAITRA	NUMERIC(18,2) = 0,
		@LAI_PHAITRA	NUMERIC(18,2) = 0,
		@TIEN_PHAITRA	NUMERIC(18,2),
		@SONGAY			DECIMAL,
		@i				DECIMAL, 
		 @MA_HDTD  NVARCHAR(20)
DECLARE CUR CURSOR FOR
SELECT MA_KHACHHANG, MA_HOPDONG_TINDUNG,SOTIEN,NGAY_GIAINGAN,NGAY_DAOHAN, LAISUAT,KY_HAN FROM HOPDONG_TINDUNG
OPEN CUR
FETCH NEXT FROM CUR
INTO @MA_KH, @MA_HDTD,@SOTIEN,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@LAISUAT,@KY_HAN
WHILE @@FETCH_STATUS = 0
BEGIN
	SET		@i	=	1
	WHILE @i <= @KY_HAN
	BEGIN
		SET @GOC_PHAITRA =@SOTIEN/@KY_HAN
		SET	@DUNO_GOC = @SOTIEN - @GOC_PHAITRA * (@i-1)
		SET @NGAY_DAUKY = DATEADD(MONTH,@i - 1,@NGAY_GIAI_NGAN)
		SET @NGAY_CUOIKY = DATEADD(DAY,-1,(DATEADD(MONTH,@i,@NGAY_GIAI_NGAN)))
		SET @SONGAY = DATEDIFF	(DAY,@NGAY_DAUKY,@NGAY_CUOIKY)
		SET @LAI_PHAITRA = @DUNO_GOC*@SONGAY/36500
		SET @TIEN_PHAITRA = @GOC_PHAITRA +@LAI_PHAITRA
		INSERT INTO KEHOACH_TRANO VALUES (@MA_KH,@MA_HDTD,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@SOTIEN,@LAISUAT,@i,@NGAY_DAUKY,@NGAY_CUOIKY,@SONGAY,@DUNO_GOC,@GOC_PHAITRA,@LAI_PHAITRA,@TIEN_PHAITRA)
		SET @i = @i + 1
	END
	UPDATE KEHOACH_TRANO SET NGAY_CUOIKY = @NGAY_DAOHAN WHERE KY_HAN = @KY_HAN
	FETCH NEXT FROM CUR
	INTO @MA_KH, @MA_HDTD,@SOTIEN,@NGAY_GIAI_NGAN,@NGAY_DAOHAN,@LAISUAT,@KY_HAN
END
CLOSE CUR;
DEALLOCATE CUR;

SELECT * FROM KEHOACH_TRANO


--DROP TABLE KEHOACH_TRANO